services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'
  rails:
    build: .
    volumes:
      - .:/rails
      - gems:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

volumes:
  redis:
  postgres:
  gems:
